REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

MAX_IMAGE_EDGE_LENGTH = 700
IMAGE_CHANS = 3
IMAGE_DTYPE = "float32"

DET_QUEUE = "det_queue"
RELA_QUEUE = "rela_queue"

BATCH_SIZE = 32
SERVER_SLEEP = 0.25
CLIENT_SLEEP = 0.25